#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use App\Commands\CreateView;
use App\Commands\GenerateProductionProject;
use App\Commands\RunPhpServer;
use App\Commands\SassCompiler;
use App\Commands\SassMaker;
use Symfony\Component\Console\Application;

// Start autoload
$loader = new Nette\Loaders\RobotLoader;
$loader->addDirectory(__DIR__ . "/commands");
$loader->setTempDirectory(__DIR__ . "/temp");
$loader->register(); // Run the RobotLoader


$application = new Application();

$application->add(new CreateView());
$application->add(new RunPhpServer());
$application->add(new GenerateProductionProject());
$application->add(new SassCompiler());
$application->add(new SassMaker());

/** @noinspection PhpUnhandledExceptionInspection */
$application->run();