#!/usr/bin/env php
<?php


use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require __DIR__ . '/vendor/autoload.php';

class DefaultCommand extends Command
{
    protected static $defaultName = 'postinit';

    protected function configure()
    {
        $this->setDescription('Outputs "Hello World"');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if (!mkdir("db") && !is_dir("db")) {
            throw new RuntimeException(sprintf('Directory "%s" was not created', "db"));
        }
        if (!mkdir("db/migrations") && !is_dir("db/migrations")) {
            throw new RuntimeException(sprintf('Directory "%s" was not created', "db/migrations"));
        }
        if (!mkdir("db/seeds") && !is_dir("db/seeds")) {
            throw new RuntimeException(sprintf('Directory "%s" was not created', "db/seeds"));
        }
        if (!mkdir("models") && !is_dir("models")) {
            throw new RuntimeException(sprintf('Directory "%s" was not created', "models"));
        }
        if (!file_exists(".env")) {
            copy(".env.example", ".env");
        }
        if (!is_dir(".git")) {
            exec("git init");
        }
        exec("git add .");
        exec("npm install");
        exec("php ada tcs:compile");
        return self::SUCCESS;
    }
}

$command = new DefaultCommand();
$application = new Application();

$application->add($command);
$application->setDefaultCommand($command->getName());

/** @noinspection PhpUnhandledExceptionInspection */
$application->run();